version: '2'
services:
  # fix-permissions:
  #   image: 'bitnami/mongodb:latest'
  #   user: root
  #   command: chown -R 1001:1001 /bitnami
  #   volumes:
  #     - ./docker-persistence:/bitnami
  mongodb:
    image: 'bitnami/mongodb:latest'
    volumes:
      - '~/docker-persistence:/bitnami/mongodb'
    # depends_on:
      # - fix-permissions
  parse:
    image: 'bitnami/parse:latest'
    environment:
      - PARSE_SERVER_MOUNT_GRAPHQL=true
      #passing these variable through from shell environment
      - PARSE_APP_ID 
      - PARSE_MASTER_KEY
    ports:
      - '1337:1337'
    volumes:
      - '~/docker-persistence:/bitnami'
    depends_on:
      - mongodb
  # fix-parse-dashboard-permissions:
  #   image: 'bitnami/parse-dashboard:1'
  #   user: root
  #   command: chown -R 1001:1001 /bitnami
  #   volumes:
  #     - ./docker-persistence/parse-dashboard:/bitnami
  parse-dashboard:
    image: 'bitnami/parse-dashboard:latest'
    ports:
      - '80:4040'
    environment:
      - PARSE_USE_HOSTNAME=yes
      - PARSE_DASHBOARD_GRAPHQL_SERVER_URL=${PARSE_HOST}/graphql
      # passing through from env
      - PARSE_APP_ID
      - PARSE_MASTER_KEY
      - PARSE_HOST
      - PARSE_DASHBOARD_APP_NAME
      - PARSE_DASHBOARD_USER
      - PARSE_DASHBOARD_PASSWORD
    volumes:
      - '~/docker-persistence:/bitnami'
    depends_on:
      - parse